Fix ESM-compatible imports in tests
.js extensions are required in ESM code (which ours is) but we need to
tell jest to actually treat TS files as ESM too. Without this change we
would get errors like

    $ /lune/lune-shipping-csv-tool/node_modules/.bin/jest src/ --coverage '--collectCoverageFrom=./src/**'
     FAIL  src/test.ts
      ● Test suite failed to run

        Cannot find module './utils.js' from 'src/test.ts'

          3 | // TODO: Remove when this is no longer needed
          4 | test('Dummy test', () => {
        > 5 |     // Boo
            |                  ^
          6 |     parseCoordinates('asd')
          7 | })
          8 |

          at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
          at Object.<anonymous> (src/test.ts:5:18)

when we added *any* imports to test.ts.